// This file is generated by Slice Machine. Update with care!

import Form from './Form';
import Hero from './Hero';
import Image from './Image';
import TextWithFeatures from './TextWithFeatures';
import TextWithImage from './TextWithImage';

export {
	Form,
	Hero,
	Image,
	TextWithFeatures,
	TextWithImage,
};

export const components = {
	form: Form,
	hero: Hero,
	image: Image,
	text_with_features: TextWithFeatures,
	text_with_image: TextWithImage,
};
